### ISSUE TITLE
Thanks! [not an issue]

### ISSUE THREAD

**Issue by ENDERZOMBI102** [MinecraftZenova/ZenovaAPI#3]
thank you guys so much for this fork and upgrade for zenova!
i was thinking of making my own modloader but then i've found zenova and then this, i really hope you guys can make
bedrock _real_ modding  "accessible" like the java one!

- ENDER

**Comment by ThePixelGamer** [comment]
Hey no problem but I will say Windows 10 modding is still going to be pretty difficult but we're trying to make it as easy as possible, progress is slow but we're still working on it 👍
